blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/MichaelRiehm/PropertyPilot/discussions
    about: Have a question or idea that isn't ready for an issue? Start a discussion.
